package ir.bigz.springbootreal.dto;

public enum ValueCondition {

    NONE, EQUAL, NOT_EQUAL, GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL,
    IN, NOT_IN, CONTAINS, STARTS_WITH, ENDS_WITH, NOT_CONTAINS, IS_NULL, IS_NOT_NULL,
    BETWEEN, NOT_BETWEEN, EXISTS, NOT_EXISTS
}
