version: '3.9'

services:
  app:
    container_name: springapp-with-db
    image: springapp:latest
    build: ./
    ports:
      - "9090:9090"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: spring-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myapp